version: 2.1

jobs:
  nodeseek:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install curl_cffi python-dotenv
      - run:
          name: Run Nodeseek signin
          command: |
            python -m nodeseek.nodeseek

  v2ex:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install curl_cffi python-dotenv
      - run:
          name: Run V2EX signin
          command: |
            python -m v2ex.v2ex

  onepoint3acres:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install requests 2captcha-python python-dotenv
      - run:
          name: Run 1point3acres signin
          command: |
            python -m onepoint3acres.onepoint3acres

  deepflood:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install curl_cffi python-dotenv
      - run:
          name: Run Deepflood signin
          command: |
            python -m deepflood.deepflood

workflows:
  # Allow manual triggers
  manual_trigger:
    jobs:
      # - nodeseek:
      #     context: checkincontext
      # - v2ex:
      #     context: checkincontext
      - onepoint3acres:
          context: checkincontext
      # - deepflood:
      #     context: checkincontext
